### ISSUE TITLE
In Part 3 - Positive Definite Matrices and Ellipsoid, Matrix Q is undefined

### ISSUE THREAD

**Issue by ifeelfree** [wingedrasengan927/Image-formation-and-camera-calibration#1]
Hi, in https://github.com/wingedrasengan927/Image-formation-and-camera-calibration/blob/master/Part%203%20-%20Positive%20Definite%20Matrices%20and%20Ellipsoid.ipynb 

```
p1 = np.vstack((y1, y2))
p2 = np.vstack((-y1, y2))

pt1 = Q @ p1
pt2 = Q @ p2

```

Q is undefined. Any ideas? Thanks.

**Comment by enrickla** [comment]
I think Q is `Q = np.linalg.inv(eigvectors)`

**Comment by wingedrasengan927** [comment]
Q is a matrix of eigenvectors.
`Q = eigvectors.T` 
Fixed now.
