### ISSUE TITLE
Extract Rotation From Matrix

### ISSUE THREAD

**Issue by enrickla** [wingedrasengan927/Image-formation-and-camera-calibration#2]
How could we extract the rotation (Quaternion) and translation to world point/rotation from the calibrated camera matrix?

Camera position seems to be accurate by doing this

> invMat = np.linalg.inv(M_)
camera_pos = (invMat [0, 3], invMat [1, 3], invMat [2, 3])
ax.scatter(*camera_pos , color="cyan")

**Comment by wingedrasengan927** [comment]
Hi @enrickla i don't think we can extract them. Also, thanks for the code on finding the camera centre.
